import 'package:dartz/dartz.dart';
import 'package:equatable/equatable.dart';

import 'package:flutter_finance_assistant/core/errors/failures.dart';
import 'package:flutter_finance_assistant/domain/entities/account.dart';
import 'package:flutter_finance_assistant/domain/repositories/account_repository.dart';
import 'package:flutter_finance_assistant/domain/usecases/usecase.dart';

/// Use case for creating a new financial account.
///
/// Handles validation and business rules for account creation:
/// - Name validation
/// - Type verification
/// - Initial balance handling
///
/// ## Example Usage
/// ```dart
/// final useCase = CreateAccountUseCase(accountRepository);
///
/// final result = await useCase(
///   CreateAccountParams(
///     userId: 'user-123',
///     name: 'Main Checking',
///     type: AccountType.bankAccount,
///     balance: 1000.00,
///     currency: 'USD',
///   ),
/// );
///
/// result.fold(
///   (failure) => showError(failure.message),
///   (account) => showSuccess('Account created: ${account.name}'),
/// );
/// ```
class CreateAccountUseCase extends UseCase<Account, CreateAccountParams> {
  final AccountRepository repository;

  CreateAccountUseCase(this.repository);

  @override
  Future<Either<Failure, Account>> call(CreateAccountParams params) async {
    // Validate user ID
    if (params.userId.isEmpty) {
      return const Left(
        ValidationFailure(
          message: 'User ID is required',
          code: 'MISSING_USER_ID',
        ),
      );
    }

    // Validate account name
    if (params.name.trim().isEmpty) {
      return const Left(
        ValidationFailure(
          message: 'Account name is required',
          code: 'MISSING_ACCOUNT_NAME',
        ),
      );
    }

    if (params.name.length > 50) {
      return const Left(
        ValidationFailure(
          message: 'Account name must be 50 characters or less',
          code: 'ACCOUNT_NAME_TOO_LONG',
        ),
      );
    }

    // Validate initial balance for credit cards/loans (should typically be negative or zero)
    if ((params.type == AccountType.creditCard ||
            params.type == AccountType.loan) &&
        params.balance > 0) {
      // This is a warning, not an error - user might be tracking available credit
      // Log or handle as needed
    }

    // Build the account entity
    final now = DateTime.now();
    final account = Account(
      id: '', // Will be generated by repository
      userId: params.userId,
      name: params.name.trim(),
      type: params.type,
      balance: params.balance,
      currency: params.currency,
      icon: params.icon,
      color: params.color,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      syncStatus: 'pending',
    );

    return repository.createAccount(account);
  }
}

/// Parameters for [CreateAccountUseCase].
class CreateAccountParams extends Equatable {
  final String userId;
  final String name;
  final AccountType type;
  final double balance;
  final String currency;
  final String icon;
  final int color;

  const CreateAccountParams({
    required this.userId,
    required this.name,
    required this.type,
    this.balance = 0.0,
    this.currency = 'USD',
    this.icon = 'account_balance_wallet',
    this.color = 0xFF2E7D6F,
  });

  @override
  List<Object?> get props => [
    userId,
    name,
    type,
    balance,
    currency,
    icon,
    color,
  ];
}
