import 'package:dartz/dartz.dart';
import 'package:equatable/equatable.dart';

import 'package:flutter_finance_assistant/core/errors/failures.dart';
import 'package:flutter_finance_assistant/domain/entities/budget.dart';
import 'package:flutter_finance_assistant/domain/repositories/budget_repository.dart';
import 'package:flutter_finance_assistant/domain/usecases/usecase.dart';

/// Use case for creating a new budget.
///
/// Handles validation for budget creation including:
/// - Amount validation
/// - Period validation
/// - Date range validation
///
/// ## Example Usage
/// ```dart
/// final useCase = CreateBudgetUseCase(budgetRepository);
///
/// final result = await useCase(
///   CreateBudgetParams(
///     categoryId: 'food-category',
///     amount: 500.00,
///     period: BudgetPeriod.monthly,
///     alertThreshold: 0.80,
///   ),
/// );
///
/// result.fold(
///   (failure) => showError(failure.message),
///   (budget) => showSuccess('Budget created: \$${budget.amount}'),
/// );
/// ```
class CreateBudgetUseCase extends UseCase<Budget, CreateBudgetParams> {
  final BudgetRepository repository;

  CreateBudgetUseCase(this.repository);

  @override
  Future<Either<Failure, Budget>> call(CreateBudgetParams params) async {
    // Validate category ID
    if (params.categoryId.isEmpty) {
      return const Left(
        ValidationFailure(
          message: 'Category is required',
          code: 'MISSING_CATEGORY',
        ),
      );
    }

    // Validate amount
    if (params.amount <= 0) {
      return const Left(
        ValidationFailure(
          message: 'Budget amount must be greater than zero',
          code: 'INVALID_AMOUNT',
        ),
      );
    }

    // Validate alert threshold
    if (params.alertThreshold < 0 || params.alertThreshold > 1) {
      return const Left(
        ValidationFailure(
          message: 'Alert threshold must be between 0 and 1',
          code: 'INVALID_THRESHOLD',
        ),
      );
    }

    // Calculate period dates
    final dates = _calculatePeriodDates(params.period, params.startDate);

    final now = DateTime.now();
    final budget = Budget(
      id: '', // Will be generated by repository
      accountId: params.accountId,
      categoryId: params.categoryId,
      amount: params.amount,
      spentAmount: 0.0,
      period: params.period,
      startDate: dates.$1,
      endDate: dates.$2,
      rollover: params.rollover,
      alertsEnabled: params.alertsEnabled,
      alertThreshold: params.alertThreshold,
      createdAt: now,
      updatedAt: now,
      syncStatus: 'pending',
    );

    return repository.createBudget(budget);
  }

  /// Calculate start and end dates for the given period
  (DateTime, DateTime) _calculatePeriodDates(
    BudgetPeriod period,
    DateTime? customStart,
  ) {
    final now = customStart ?? DateTime.now();

    switch (period) {
      case BudgetPeriod.daily:
        final start = DateTime(now.year, now.month, now.day);
        return (start, start.add(const Duration(days: 1)));

      case BudgetPeriod.weekly:
        final start = now.subtract(Duration(days: now.weekday - 1));
        final startDate = DateTime(start.year, start.month, start.day);
        return (startDate, startDate.add(const Duration(days: 7)));

      case BudgetPeriod.biweekly:
        final start = now.subtract(Duration(days: now.weekday - 1));
        final startDate = DateTime(start.year, start.month, start.day);
        return (startDate, startDate.add(const Duration(days: 14)));

      case BudgetPeriod.monthly:
        final start = DateTime(now.year, now.month, 1);
        final end = DateTime(now.year, now.month + 1, 0);
        return (start, end);

      case BudgetPeriod.quarterly:
        final quarter = ((now.month - 1) ~/ 3);
        final start = DateTime(now.year, quarter * 3 + 1, 1);
        final end = DateTime(now.year, quarter * 3 + 4, 0);
        return (start, end);

      case BudgetPeriod.yearly:
        final start = DateTime(now.year, 1, 1);
        final end = DateTime(now.year, 12, 31);
        return (start, end);
    }
  }
}

/// Parameters for [CreateBudgetUseCase].
class CreateBudgetParams extends Equatable {
  final String? accountId;
  final String categoryId;
  final double amount;
  final BudgetPeriod period;
  final DateTime? startDate;
  final bool rollover;
  final bool alertsEnabled;
  final double alertThreshold;

  const CreateBudgetParams({
    this.accountId,
    required this.categoryId,
    required this.amount,
    this.period = BudgetPeriod.monthly,
    this.startDate,
    this.rollover = false,
    this.alertsEnabled = true,
    this.alertThreshold = 0.80,
  });

  @override
  List<Object?> get props => [
    accountId,
    categoryId,
    amount,
    period,
    startDate,
    rollover,
    alertsEnabled,
    alertThreshold,
  ];
}
