import 'package:dartz/dartz.dart';
import 'package:equatable/equatable.dart';

import 'package:flutter_finance_assistant/core/errors/failures.dart';
import 'package:flutter_finance_assistant/domain/entities/transaction.dart';
import 'package:flutter_finance_assistant/domain/repositories/transaction_repository.dart';
import 'package:flutter_finance_assistant/domain/usecases/usecase.dart';

/// Use case for creating a new financial transaction.
///
/// Handles business logic for:
/// - Transaction validation
/// - Amount verification
/// - Category assignment
/// - Transfer handling (creates paired transactions)
///
/// ## Example Usage
/// ```dart
/// final useCase = CreateTransactionUseCase(transactionRepository);
///
/// final result = await useCase(
///   CreateTransactionParams(
///     accountId: 'account-123',
///     categoryId: 'food-category',
///     amount: 25.50,
///     type: TransactionType.expense,
///     description: 'Lunch at restaurant',
///     date: DateTime.now(),
///   ),
/// );
///
/// result.fold(
///   (failure) => showError(failure.message),
///   (transaction) => showSuccess('Transaction created: ${transaction.id}'),
/// );
/// ```
class CreateTransactionUseCase
    extends UseCase<Transaction, CreateTransactionParams> {
  final TransactionRepository repository;

  CreateTransactionUseCase(this.repository);

  @override
  Future<Either<Failure, Transaction>> call(
    CreateTransactionParams params,
  ) async {
    // Validate amount
    if (params.amount <= 0) {
      return const Left(
        ValidationFailure(
          message: 'Amount must be greater than zero',
          code: 'INVALID_AMOUNT',
        ),
      );
    }

    // Validate account ID
    if (params.accountId.isEmpty) {
      return const Left(
        ValidationFailure(
          message: 'Account ID is required',
          code: 'MISSING_ACCOUNT_ID',
        ),
      );
    }

    // Validate category ID
    if (params.categoryId.isEmpty) {
      return const Left(
        ValidationFailure(
          message: 'Category ID is required',
          code: 'MISSING_CATEGORY_ID',
        ),
      );
    }

    // For transfers, validate target account
    if (params.type == TransactionType.transfer &&
        (params.toAccountId == null || params.toAccountId!.isEmpty)) {
      return const Left(
        ValidationFailure(
          message: 'Target account is required for transfers',
          code: 'MISSING_TARGET_ACCOUNT',
        ),
      );
    }

    // Cannot transfer to the same account
    if (params.type == TransactionType.transfer &&
        params.toAccountId == params.accountId) {
      return const Left(
        ValidationFailure(
          message: 'Cannot transfer to the same account',
          code: 'SAME_ACCOUNT_TRANSFER',
        ),
      );
    }

    // Build the transaction entity
    final now = DateTime.now();
    final transaction = Transaction(
      id: '', // Will be generated by repository
      accountId: params.accountId,
      categoryId: params.categoryId,
      amount: params.amount,
      type: params.type,
      description: params.description,
      date: params.date,
      receiptUrl: params.receiptUrl,
      location: params.location,
      tags: params.tags,
      isRecurring: params.isRecurring,
      recurringId: params.recurringId,
      toAccountId: params.toAccountId,
      createdAt: now,
      updatedAt: now,
      syncStatus: 'pending',
    );

    return repository.createTransaction(transaction);
  }
}

/// Parameters for [CreateTransactionUseCase].
class CreateTransactionParams extends Equatable {
  final String accountId;
  final String categoryId;
  final double amount;
  final TransactionType type;
  final String? description;
  final DateTime date;
  final String? receiptUrl;
  final String? location;
  final List<String> tags;
  final bool isRecurring;
  final String? recurringId;
  final String? toAccountId;

  const CreateTransactionParams({
    required this.accountId,
    required this.categoryId,
    required this.amount,
    required this.type,
    this.description,
    required this.date,
    this.receiptUrl,
    this.location,
    this.tags = const [],
    this.isRecurring = false,
    this.recurringId,
    this.toAccountId,
  });

  @override
  List<Object?> get props => [
    accountId,
    categoryId,
    amount,
    type,
    description,
    date,
    receiptUrl,
    location,
    tags,
    isRecurring,
    recurringId,
    toAccountId,
  ];
}
