import 'package:dartz/dartz.dart';
import 'package:equatable/equatable.dart';

import 'package:flutter_finance_assistant/core/errors/failures.dart';
import 'package:flutter_finance_assistant/domain/entities/category.dart';
import 'package:flutter_finance_assistant/domain/repositories/category_repository.dart';
import 'package:flutter_finance_assistant/domain/usecases/usecase.dart';

/// Use case for creating a custom category.
///
/// Only user-created categories can be created through this use case.
/// System categories are created through [InitializeDefaultCategoriesUseCase].
///
/// ## Example Usage
/// ```dart
/// final useCase = CreateCategoryUseCase(categoryRepository);
///
/// final result = await useCase(
///   CreateCategoryParams(
///     userId: 'user-123',
///     name: 'Subscriptions',
///     icon: 'subscriptions',
///     color: 0xFF6C5CE7,
///     type: CategoryType.expense,
///   ),
/// );
///
/// result.fold(
///   (failure) => showError(failure.message),
///   (category) => showSuccess('Category created: ${category.name}'),
/// );
/// ```
class CreateCategoryUseCase extends UseCase<Category, CreateCategoryParams> {
  final CategoryRepository repository;

  CreateCategoryUseCase(this.repository);

  @override
  Future<Either<Failure, Category>> call(CreateCategoryParams params) async {
    // Validate user ID
    if (params.userId.isEmpty) {
      return const Left(
        ValidationFailure(
          message: 'User ID is required',
          code: 'MISSING_USER_ID',
        ),
      );
    }

    // Validate name
    if (params.name.trim().isEmpty) {
      return const Left(
        ValidationFailure(
          message: 'Category name is required',
          code: 'MISSING_CATEGORY_NAME',
        ),
      );
    }

    if (params.name.length > 30) {
      return const Left(
        ValidationFailure(
          message: 'Category name must be 30 characters or less',
          code: 'CATEGORY_NAME_TOO_LONG',
        ),
      );
    }

    // Build the category entity
    final category = Category(
      id: '', // Will be generated by repository
      userId: params.userId,
      name: params.name.trim(),
      icon: params.icon,
      color: params.color,
      type: params.type,
      parentId: params.parentId,
      isSystem: false, // User-created categories are never system
      createdAt: DateTime.now(),
      syncStatus: 'pending',
    );

    return repository.createCategory(category);
  }
}

/// Parameters for [CreateCategoryUseCase].
class CreateCategoryParams extends Equatable {
  final String userId;
  final String name;
  final String icon;
  final int color;
  final CategoryType type;
  final String? parentId;

  const CreateCategoryParams({
    required this.userId,
    required this.name,
    this.icon = 'category',
    this.color = 0xFF6C5CE7,
    this.type = CategoryType.expense,
    this.parentId,
  });

  @override
  List<Object?> get props => [userId, name, icon, color, type, parentId];
}
